program: train.py
method: random
metric:
  name: val_balanced_accuracy
  goal: maximize
parameters:
  model_name:
    values: [
    resnext101_32x8d.fb_swsl_ig1b_ft_in1k, 
    resnet50.fb_swsl_ig1b_ft_in1k,
    efficientnet_es.ra_in1k,
    caformer_b36.sail_in22k_ft_in1k,
    caformer_s36.sail_in22k_ft_in1k,
    tiny_vit_21m_224.dist_in22k_ft_in1k
    ] 
  head_dropout:
    min: 0.0
    max: 0.8
  loss:
    values: ['focal_loss']
  optimizer:
    values: ['adam', 'adamw']
  backbone_lr:
    min: 1e-7
    max: 1e-5
  head_lr:
    min: 1e-5
    max: 1e-3
  batch_size:
    values: [32, 64, 128, 256]